version: '2'
services:
  smtp:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
  httpd:
    image: hysryt/php-for-mailcatcher:7.2-apache
    ports:
      - '1234:80'
    volumes:
      - ./public:/var/www/html